# ============================================================
#  Microservicio: JUEGOS / CATALOGO  (puerto 8084)
# ============================================================
spring.application.name=juegos-service
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/juegos_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


# ----- URLs de los microservicios remotos (Feign) -----
servicios.desarrolladoras.url=http://localhost:8082
servicios.categorias.url=http://localhost:8083

# ----- Timeouts de Feign (manejo de comunicacion remota) -----
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=3000

logging.level.com.videojuegos=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
